spring.application.name=inventory

# DEFAULT PROFILE (for local run)
# Switch profile manually
spring.profiles.active=dev
#spring.profiles.active=prod
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#unauth url
security.permit-all=/auth/login

#toke expire time (12 h/ 5m/ 10s/ 1d)
jwt.expiration= 12h