spring.application.name=inventory

# DEFAULT PROFILE (for local run)
# Switch profile manually
spring.profiles.active=dev
#spring.profiles.active=prod
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect