server.port=8080

spring.datasource.url=jdbc:mysql://187.127.154.62:3306/inventory_dev
spring.datasource.username=inventory_user
spring.datasource.password=Str0ng@Pass123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Pool size
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Max lifetime (30 min)
spring.datasource.hikari.max-lifetime=1800000

# Idle timeout (10 min)
spring.datasource.hikari.idle-timeout=600000

# Connection timeout (30 sec)
spring.datasource.hikari.connection-timeout=30000

# Keep connection alive (5 min)
spring.datasource.hikari.keepalive-time=300000

# Validation timeout
spring.datasource.hikari.validation-timeout=5000